### ISSUE TITLE
I can't upload an image in any PageData..

### ISSUE THREAD

**Issue by jvalle63** [xzripper/flet_navigator#10]
**Describe your problem:**
First of all, I would like to congratulate you. Flet_Navigator is an excellent product and very easy to use. I just made software for a client using it, and the usability and performance really captivated me.
Now, I have a problem... I need to upload an image using "assets" and I can't...
I set the asset path, but when I try to load an image on a specific PageData or on the main page (ft.page) the image does not appear.

**Reproducing the problem:**
This code bellow is what I need. I´m not using Flet_Navigatot in it .It's just to you understand the requirement.

import flet as ft
from pathlib import Path
assets=f'{Path(__file__).parent}\\atelier-costura'
logo=f'\\manual\\logo-4.jpg'
print(dir)

def main(page: ft.Page):
    page.title = "Images Example"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.padding = 50
    page.update()

    img = ft.Image(
        src=logo,
        width=80,
        height=80,
        fit=ft.ImageFit.COVER,
        border_radius=1,
    )
    texto=ft.Text('Atelier Tesoura Mágica',font_family='tahoma',size=20,color=ft.colors.PINK, )
  
    cabecalho=ft.ResponsiveRow([ft.Column(col={"xs":4,"sm": 3, "md":2 , "xl":1},controls=[img]),
                                ft.Column(col={"xs":8,"sm": 6, "md": 5, "xl": 4},controls=[texto]),
                                ],
                               vertical_alignment=ft.CrossAxisAlignment.CENTER,alignment='left')
    page.add(cabecalho)

    page.update()

ft.app(target=main, view=ft.AppView.WEB_BROWSER,assets_dir=assets)

**Media (optional):**
Screenshot or video..

**flet_navigator version, flet version, OS:**
Name: flet_navigator
Version: 2.6.5

Name: flet
Version: 0.21.1

Windows 10

**Additional:**
...

**Comment by xzripper** [comment]
Thank you, I'm glad you like my project! Also thanks for reporting issue!

-----

![Code_aTdqadAleB](https://github.com/xzripper/flet_navigator/assets/94743980/956b5433-5f33-430f-8e14-0e98cf21b975)

I have checked that there are no conflicts between FletNavigator and Flet Assets, so there are no problems. Probably you're misspelled path to `logo`, also could you provide more information? Is there any errors? Can I see full code?

P.S You're not adding `img` control to page in your code example, maybe there is an issue?

**Comment by jvalle63** [comment]
I'm going to test an example using Flet_Navigator.
I don't send my software script, because it has 1900  code lines...

**Comment by jvalle63** [comment]
Ok, it worked fine. Now I'll have to find out what is going on with my script.
thanks for your help.

**Comment by xzripper** [comment]
I am glad you had your issue fixed! Can I close this issue?
