### ISSUE TITLE
[ISSUE] Container "expand=True" doesn't work

### ISSUE THREAD

**Issue by Dario-Ciceri** [xzripper/flet_navigator#11]
**Describe your problem:**
If you try to expand Container layout it doesn't work, is it a known bug (flexible support)?

**Reproducing the problem:**
Just try to expand a Container with expand=True

**Media (optional):**
<img width="506" alt="image" src="https://github.com/xzripper/flet_navigator/assets/35496439/0d8c7ae6-ec96-4a27-bd64-7e40d7a0f517">

**flet_navigator version, flet version, OS:**
`FletNavigator version 2.6.5, Flet Version 0.20.2, OS Windows 11 Home 10.0.22631`

**Additional:**
...

**Comment by xzripper** [comment]
Hello! Thanks for reporting an issue!

-----

Actually, I don't think its FletNavigator issue, at least I think so.

```python
from flet import app, Page, Container, Row, TextField


def main(page: Page) -> None:
    page.add(Container(Row([TextField(hint_text='Text...'), TextField(hint_text='Text...')]), expand=True))

app(main)
```

![Screenshot_3](https://github.com/xzripper/flet_navigator/assets/94743980/9ce8d7b4-8b67-4695-bd60-2568749d5833)
*No FletNavigator used...*

I think we can investigate, would you mind sending example/full code?

**Comment by Dario-Ciceri** [comment]
```
from flet import *
from src.classes.widgets import *

class LoginPage(UserControl):
    def __init__(self, page: Page):
        super().__init__()
        self.page = page
        self.username_field = TextField(
            **login_interface_style.get("username_field"),
            bgcolor=colors.with_opacity(0.7,colors.SURFACE),
            on_change=self.validate,
        )
        self.password_field = TextField(
            **login_interface_style.get("password_field"),
            bgcolor=colors.with_opacity(0.7,colors.SURFACE),
            on_change=self.validate,
            on_submit=self.submit,
        )
        self.login_button = ElevatedButton(
            **login_interface_style.get("login_button"), on_click=self.submit,
            bgcolor=colors.with_opacity(0.7,colors.SURFACE),
        )
        self.remember_device_checkbox = Checkbox(
            **login_interface_style.get("remember_device_checkbox")
        )
        self.exit_button = ElevatedButton(
            **login_interface_style.get("exit_button"), 
            on_click=lambda _: self.page.window_close(),
        )
        self.login_page_layout = Column(
                [
                    Container(
                        Column(
                            [
                                Topbar(page),
                                Container(
                                    Column([self.username_field,self.password_field,self.login_button],alignment=MainAxisAlignment.CENTER),
                                    alignment=alignment.center,
                                    expand=True,
                                ),
                            ],
                            expand=True,
                            alignment=MainAxisAlignment.CENTER
                        ),
                        image_src=r"V2\assets\login_background.png",
                        image_fit=ImageFit.COVER,
                        expand=True,
                        alignment=alignment.center
                    )
                ],
                expand=True,
                alignment=MainAxisAlignment.CENTER
            )
    
    def build(self):
        return self.login_page_layout

    def validate(self, e: ControlEvent):
        self.password_field.error_text = None
        if self.password_field.value and self.username_field.value:
            self.login_button.disabled = False
        else:
            self.login_button.disabled = True

        self.update()

    def submit(self, e: ControlEvent) -> bool:
       pass
```

**Comment by Dario-Ciceri** [comment]
```
login_interface_style = {
    "title": {
        "content": Text("Company name"),
        "bgcolor": "#1d1e2a",
        "width": 300,
        "height": 30,
        "alignment": alignment.center,
    },
    "username_field": {
        "width": 355,
        "label": "Username",
    },
    "password_field": {
        "width": 355,
        "label": "Password",
        "password": True,
        "can_reveal_password": True,
    },
    "login_button": {"text": "Login", "width": 355, "disabled": True},
    "remember_device_checkbox": {
        "label": "Non chiedere più la password",
        "value": False,
        "width": 355,
    },
    "exit_button": {
        "text": "Esci",
        "width": 355,
        "color": colors.RED,
    },
    "interface_column": {
        "alignment": MainAxisAlignment.CENTER,
        "horizontal_alignment": MainAxisAlignment.CENTER,
    },
    "interface_container": {
        "gradient": RadialGradient(
            center=Alignment(0, -1.25),
            radius=2.4,
            colors=[
                "#42445f",
                "#393b52",
                "#33354a",
                "#2f3143",
                "#292b3c",
                "#222331",
                "#1a1a25",
                "#1a1b26",
                "#21222f",
                "#1d1e2a",
            ],
        ),
        "width": 300,
        "height": 270,
        "alignment": alignment.center,
    },
    "interface": {
        "spacing": 0,
    },
}
```

**Comment by Dario-Ciceri** [comment]
I also wanted to ask you this, I decided to use your library because I find it well done and especially appreciate that, unlike Flet's basic navigator, it doesn't break anything... what I mean is that I tried to do the same thing with Flet but punctually the reference to the page between different views becomes None and I don't understand why, to give you an example: login page ---> login done goes to home page ---> error if you do a page resize that says NoneType doesn't have the width parameter (so it loses the reference to the current page). .. your library on the other hand requires to send the reference to the current page and in fact this solves my problem thus being able to not only make a multi page app but also with pages of different looks and sizes... do you happen to know what could be the reason why on Flet instead everything breaks, what did you do differently?

I hope I explained myself well, in the meantime thank you!

**Comment by xzripper** [comment]
> I also wanted to ask you this, I decided to use your library because I find it well done and especially appreciate that, unlike Flet's basic navigator, it doesn't break anything... what I mean is that I tried to do the same thing with Flet but punctually the reference to the page between different views becomes None and I don't understand why, to give you an example: login page ---> login done goes to home page ---> error if you do a page resize that says NoneType doesn't have the width parameter (so it loses the reference to the current page). .. your library on the other hand requires to send the reference to the current page and in fact this solves my problem thus being able to not only make a multi page app but also with pages of different looks and sizes... do you happen to know what could be the reason why on Flet instead everything breaks, what did you do differently?
> 
> I hope I explained myself well, in the meantime thank you!

Thank you, I very appreciate that and I am really glad that you like my library!

Navigation support in Flet is lacking and attempts to implement it are unstable. Separate support for this mechanic was necessary. Navigation in FletNavigator is not straightforward. In VirtualFletNavigator, the library uses a virtual path, making it easier to implement. However, this approach eliminates the possibility of using URL parameters and, most importantly, there are no public routes available. This means that you cannot share a link leading to this route. In the public navigator, the page route is accessed through 'page.route'. FletNavigator intercepts route changes from external sources, such as changes made in the search bar. Additionally, the 'navigate' function is used to modify the route. Each page is linked to a specific route, and when FletNavigator detects that the current route corresponds to a linked page, it calls the corresponding function. The main code for the page is written within this function.

**Comment by Dario-Ciceri** [comment]
> > I also wanted to ask you this, I decided to use your library because I find it well done and especially appreciate that, unlike Flet's basic navigator, it doesn't break anything... what I mean is that I tried to do the same thing with Flet but punctually the reference to the page between different views becomes None and I don't understand why, to give you an example: login page ---> login done goes to home page ---> error if you do a page resize that says NoneType doesn't have the width parameter (so it loses the reference to the current page). .. your library on the other hand requires to send the reference to the current page and in fact this solves my problem thus being able to not only make a multi page app but also with pages of different looks and sizes... do you happen to know what could be the reason why on Flet instead everything breaks, what did you do differently?
> > I hope I explained myself well, in the meantime thank you!
> 
> Thank you, I very appreciate that and I am really glad that you like my library!
> 
> Navigation support in Flet is lacking and attempts to implement it are unstable. Separate support for this mechanic was necessary. Navigation in FletNavigator is not straightforward. In VirtualFletNavigator, the library uses a virtual path, making it easier to implement. However, this approach eliminates the possibility of using URL parameters and, most importantly, there are no public routes available. This means that you cannot share a link leading to this route. In the public navigator, the page route is accessed through 'page.route'. FletNavigator intercepts route changes from external sources, such as changes made in the search bar. Additionally, the 'navigate' function is used to modify the route. Each page is linked to a specific route, and when FletNavigator detects that the current route corresponds to a linked page, it calls the corresponding function. The main code for the page is written within this function.

And I think that's much better, I use flet for desktop and mobile not web so that's perfect for me

**Comment by Dario-Ciceri** [comment]
> update:
> 
> ```
> self.login_page_layout = Container(
>                         Column(
>                             [
>                                 #Topbar(self.page),
>                                 #Container(
>                                     Column([self.username_field,self.password_field,self.login_button],alignment=MainAxisAlignment.CENTER),
>                                     #alignment=alignment.center,
>                                     #expand=True,
>                                 #),
>                             ],
>                             #expand=True,
>                            # alignment=MainAxisAlignment.CENTER
>                         ),
>                         image_src=r"V2\assets\login_background.png",
>                         image_fit=ImageFit.COVER,
>                         expand=True,
>                         alignment=alignment.center
>                     )
> ```
> 
> Better but not expanded... <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/35496439/313199735-5cf9c34f-1c73-4eec-be5a-70314f0665d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDc3MzEsIm5iZiI6MTcxMDUwNzQzMSwicGF0aCI6Ii8zNTQ5NjQzOS8zMTMxOTk3MzUtNWNmOWMzNGYtMWM3My00ZWVjLWJlNWEtNzAzMTRmMDY2NWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEyNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YjRlZDBjNTE4NzE1OGNhNzlhYjhhMTRhNDkxOTY0YjIxZmQwNzcwMDdhOThjZGFjMGM1NTk1Njg5YzljZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yMvFa_HXFgCvV5pnoSIhPl9JRmSpXEJ7pYFzjsJgdHw">

btw, before using your library it was working so it must be something with your page layout but it doesn't matter I just need to adapt it

**Comment by Dario-Ciceri** [comment]
this way works but if I expand the internal container it breaks everything!

Also, the external container doesn't expand...

```
self.login_page_layout = Container(
                        Column(
                            [
                                #Topbar(self.page),
                                Container(
                                    Column([self.username_field,self.password_field,self.login_button],alignment=MainAxisAlignment.CENTER),
                                    alignment=alignment.center,
                                    #expand=True,
                                ),
                            ],
                            expand=True,
                            alignment=MainAxisAlignment.CENTER
                        ),
                        image_src=r"V2\assets\login_background.png",
                        image_fit=ImageFit.COVER,
                        expand=True,
                        alignment=alignment.center
                    )
```

**Comment by xzripper** [comment]
FletNavigator just renders the page, but doesn't add any changes. Perhaps the problem is in the front-end of the page, or when the page is refreshed, the past settings for the page are lost. Honestly I have no idea in Flet front-end, stylings, etc... I'll keep investigating in this issue.

**Comment by Dario-Ciceri** [comment]
> FletNavigator just renders the page, but doesn't add any changes. Perhaps the problem is in the front-end of the page, or when the page is refreshed, the past settings for the page are lost. Honestly I have no idea what's happening, I have no experience in Flet front-end, styling, etc... I'll keep investigating in this issue.

For now, I could use height=page.window_height and update this value on_resize

**Comment by Dario-Ciceri** [comment]
> You mean this fixes the issue?

it's a workaround but still not really flexible because you have a little delay I believe

**Comment by xzripper** [comment]
Hmm, is it possible for you to send me full project code and resources? Because I can't run code because it has lack of images and other parts of code.

**Comment by Dario-Ciceri** [comment]
> Hmm, is it possible for you to send me full project code and resources? Because I can't run code because it has lack of images and other parts of code

Unfortunately I don't think I can do it, I didn't send you drafts to complicate your life but just because I am limited on what material to share, I understand if you can't help me but if I find the solution I will share it here for everyone

**Comment by xzripper** [comment]
Yep, sure I understand that. I will continue investigating. Good luck!

**Comment by Dario-Ciceri** [comment]
I can share with you this solution:
```
self.page.on_resize = self.on_resize
```
```
def on_resize(self,e):
        self.login_page_layout.height = self.page.window_height
        self.update()
```

**Comment by Dario-Ciceri** [comment]
ok, useful update:
I tried to come back to my original code before using your library:
the good news is that I think it's not your library fault but the layout type I used...
before your library I was using class LoginPage(View) and it works very well, but your library requires UserControl and that breaks everything, I tried without your library and with class LoginPage(userControl) and that breaks everything too!
So it looks like I can't use UserControl and maybe it's my fault

**Comment by Dario-Ciceri** [comment]
so now my question is:
how do I correctly define a page layout with your library?
It doesn't accept the View type, any ideas?

**Comment by Dario-Ciceri** [comment]
well, I think we can close this

**Comment by xzripper** [comment]
I glad you got your issue fixed! Congratulations and good luck!
