### ISSUE TITLE
A possible performance issue when returning to the previous page

### ISSUE THREAD

**Issue by jvalle63** [xzripper/flet_navigator#12]
**Describe your problem:**
I'm really not sure if the bug is in Flet_Navigator. I just want you to help me think about the source of the problem.
The system performs Kanban control of work orders
My page structure:
Home - Login/pawwword. It is only assessed when we enter the system.
Page1 - Entry page containing a Datatable of work orders whose origin is a dataframe, which is assembled by importing values from the Postgres database.
Page2 - Another Datatable with customer data imported from a Postgres database
Page3 - Analytical data of the work order, containing two dataframes with little data.

The problem occurs when I return from page 2 or 3 to page 1
Currently the service order datatable has 180 records...

**Reproducing the problem:**
The code is too big. Maybe I could post a islice of it, if you want...

**Media (optional):**
Screenshot or video..

**flet_navigator version, flet version, OS:**

`Name: flet_navigator
Version: 2.6.5

Name: flet
Version: 0.21.1

Windows10 / Apache / Android

**Additional:**
...

**Comment by jvalle63** [comment]
I forgot to say that I call the database in every page, since I had problems with database disconnection, because I called it only at beginning of the script.

**Comment by xzripper** [comment]
What problem occurs when changing pages? What problems with database disconnection?

**Comment by jvalle63** [comment]
The database connection is charged per use. So, if you don't use or close the app, the bank automatically disconnects. I'm using Replit (https://replit.com).
To avoid disconnection problem, I put  the database connection in every page, and it is working 100%. I didn't try to put the connection only in ft,page...

**Comment by jvalle63** [comment]
I'm almost sure that the performance problem is within the data load in the Dataframe and Datatable...
So I think there´s no relation with flet_navigator... 

But that's not good news for me, (I know it is for you, Lol), because it could be a structural limitation of Flet.
I'll open a ticket there. Thanks a Lot for your help.

If you can, take a look at this issue of connecting to the database..

**Comment by xzripper** [comment]
I'll take a look!
