### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by Harfho** [xzripper/flet_navigator#13]
**Describe your problem:**
Getting this error 
    from flet_navigator import VirtualFletNavigator, Any, ROUTE_404
  File "C:\Users\Harfho\.virtualenvs\fletdemo-ECSyV_o1\lib\site-packages\flet_navigator\__init__.py", line 19, in <module>
    _global_templates: dict[str, 'TemplateDefinition'] = {}
TypeError: 'type' object is not subscriptable

**Reproducing the problem:**
from flet import app, Text

from flet_navigator import PageData, render, anon, route

@route('/')
def main_page(pg: PageData) -> None:
  pg.add(Text('Main Page!')) # or `pg.page.add`.

@route('second_page')
def second_page(pg: PageData) -> None:
  ... # Second page content.

app(anon(render, virtual=True))

**Media (optional):**
![image](https://github.com/xzripper/flet_navigator/assets/39716223/f19fa5fa-6877-4441-90c5-a5e16be15de1)

**flet_navigator version, flet version, OS:**
flet 0.21.2 
flet_navigator 2.7.5

**Additional:**
...

**Comment by xzripper** [comment]
Hello! Thanks for reporting this issue? I have this example running successfully, what is your Python version?

**Comment by xzripper** [comment]
It's Python 3.8 issue, in Python 3.9 everything works well! Try updating Python to 3.9
