### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by sshadowfiend** [xzripper/flet_navigator#17]
Hi! I am developing an application using Flet and flet_navigator. When creating a VirtualFletNavigator object, I set the animation of the transition between pages using the navigator_animation method, however, when launching the application, the animation changes from time to time to the standard one, and this happens at a random moment. To better understand the situation, I created a test application with only 2 pages, each of which includes only a button to go to another page, nothing else. However, the problem is still the same.

My code: 

from flet_navigator import *
import flet as ft

@route('/')
def first(pg: PageData) -> None:
    
    def go_second(e):
        print("Navigating to /second")
        pg.navigator.navigate('/second', page=pg.page)
    
    pg.page.bgcolor = ft.colors.BLUE
    pg.page.add(
        ft.ElevatedButton('go second', on_click=go_second)
    )

@route('/second')
def second(pg: PageData) -> None:
    
    def go_first(e):
        print("Navigating to /")
        pg.navigator.navigate('/', page=pg.page)
    
    pg.page.bgcolor = ft.colors.BLUE
    pg.page.add(
        ft.ElevatedButton('go first', on_click=go_first)
    )

def main(page: ft.Page) -> None:
    navigator = VirtualFletNavigator(
        routes={
            '/': first,
            '/second': second
        },
        navigator_animation=NavigatorAnimation(NavigatorAnimation.FADE)
    )

    navigator.render(page)

if __name__ == '__main__':
    ft.app(target=main)

**Comment by xzripper** [comment]
I'll have a look at that in an hour!

**Comment by xzripper** [comment]
```python
from flet_navigator import *

from flet import app, ElevatedButton, colors

@route('/')
def first(pg: PageData) -> None:
    pg.add(ElevatedButton('Go to second page.', on_click=anon(lambda: (pg.navigate('second'), setattr(pg.page, 'bgcolor', colors.BLUE)))))

@route('second')
def second(pg: PageData) -> None:
    pg.add(ElevatedButton('Go to home.', on_click=anon(lambda: (pg.navigate_homepage(), setattr(pg.page, 'bgcolor', colors.RED)))))

app(lambda page: render(
    page,
    route_changed_handler=lambda route: print(f'Route: {route}'),
    navigator_animation=NavigatorAnimation(NavigatorAnimation.FADE),
    virtual=True)
)
```
I'm sorry, but I can't find any issues here? Animation time seems symmetrical to me

**Comment by xzripper** [comment]
![QbVz3Go2Vh](https://github.com/user-attachments/assets/f1eb5846-a39b-4b3a-ae43-7109ced02b47)
Also, animation isn't very well developed, so problems with it aren't new to me

**Comment by xzripper** [comment]
Oh, I got the issue, to be honest, I can't fix this problem, I recommend you disabling this feature by setting animation to `NavigatorAnimation.NONE` (`navigator_animation=NavigatorAnimation(NavigatorAnimation.NONE)`)

**Comment by xzripper** [comment]
In my opinion Flet does not support animations during page transitions at all, and the current implementation is more superficial and unstable, and the implementation of such features you need to go deeper into the code of Flet itself/

**Comment by sshadowfiend** [comment]
Okay, thank you, bro!
