### ISSUE TITLE
 flet_navigator error

### ISSUE THREAD

**Issue by Plumpplump** [xzripper/flet_navigator#3]
Hi , I am interested in the flet_navigator and just tried the example (I downloaded it and named it testrouting.py) . I have this error. I tested on Linux Mint and Windows 11, using flet 0.11.0 and python 3.12.

 File "/home/python_projects/flet_projects/.venv/lib/python3.12/site-packages/flet_runtime/app.py", line 359, in on_session_created
    session_handler(page)
  File "/home/python_projects/flet_projects/testrouting.py", line 72, in main
    flet_navigator.render(page) # Render main page.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/python_projects/flet_projects/.venv/lib/python3.12/site-packages/flet_navigator/__init__.py", line 83, in render
    self.routes[route](page, self, args, self._nav_previous_routes[-2] if len(self._nav_previous_routes) >= 2 else '/', route_parameters)
TypeError: main_page() takes 3 positional arguments but 5 were given

**Comment by xzripper** [comment]
I'm very sorry, but after major release v2.0.1 I forgot to specify this example as deprecated.
You can try example from [documentantion](https://github.com/xzripper/flet_navigator/blob/main/flet-navigator-docs.md#virtualfletnavigator) for `VirtualFletNavigator`:
```
from flet import app, Page

from flet_navigator import VirtualFletNavigator, Any, ROUTE_404

def main_page(page: Page, navigator: VirtualFletNavigator, args: tuple[Any], previous: str, parameters: dict[str, Any]) -> None:
    ... # Main page content.

def second_page(page: Page, navigator: VirtualFletNavigator, args: tuple[Any], previous: str, parameters: dict[str, Any]) -> None:
    ... # Second page content.

def route_404(page: Page, navigator: VirtualFletNavigator, args: tuple[Any], previous: str, parameters: dict[str, Any]) -> None:
    ... # 404 Page Content.

def main(page: Page) -> None:
    # Initialize navigator.
    flet_navigator = VirtualFletNavigator(
        {
            '/': main_page, # Main page route.
            'second_page': second_page, # Second page route.
            ROUTE_404: route_404 # 404 page route.
        }, lambda route: print(f'Route changed!: {route}') # Route change handler (optional).
    )

    flet_navigator.render(page) # Render current page.

app(target=main)
```
In next release the example will be fixed.

**Comment by xzripper** [comment]
Or if you want to use `FletNavigator` (non-virtual) (example from [documentation](https://github.com/xzripper/flet_navigator/blob/main/flet-navigator-docs.md#fletnavigator)):
```python
from flet import app, Page, WEB_BROWSER

from flet_navigator import FletNavigator, Any, ROUTE_404


def main_page(page: Page, navigator: FletNavigator, args: tuple[Any], previous: str, parameters: dict[str, Any]) -> None:
    ... # Main page content.

def second_page(page: Page, navigator: FletNavigator, args: tuple[Any], previous: str, parameters: dict[str, Any]) -> None:
    ... # Second page content.

def route_404(page: Page, navigator: FletNavigator, args: tuple[Any], previous: str, parameters: dict[str, Any]) -> None:
    ... # 404 page content.

def main(page: Page) -> None:
    # Initialize navigator.
    flet_navigator = FletNavigator(page, # Specify page.
        {
            '/': main_page, # Main page route,
            'second_page': second_page, # Second page route,
            ROUTE_404: route_404 # 404 page route
        }, lambda route: print(f'Route changed!: {route}') # Route change handler (optional).
    )

    # Render current page.
    flet_navigator.render(page)

app(target=main, view=WEB_BROWSER) # Non-Virtual Navigator recommended in web.
```

**Comment by xzripper** [comment]
After `v2.1.1` update:
```python
from flet import app, Page

from flet_navigator import VirtualFletNavigator, PageData, ROUTE_404

def main_page(pg: PageData) -> None:
    ... # Main page content.

def second_page(pg: PageData) -> None:
    ... # Second page content.

def route_404(pg: PageData) -> None:
    ... # 404 Page Content.

def main(page: Page) -> None:
    # Initialize navigator.
    flet_navigator = VirtualFletNavigator(
        {
            '/': main_page, # Main page route.
            'second_page': second_page, # Second page route.
            ROUTE_404: route_404 # 404 page route.
        }, lambda route: print(f'Route changed!: {route}') # Route change handler (optional).
    )

    flet_navigator.render(page) # Render current page.

app(target=main)
```

**Comment by Plumpplump** [comment]
It would be helpful to show how to pass data and/or some complex data structure between pages in the example. Thanks.

**Comment by xzripper** [comment]
Transferring simple  data (strings, ints, etc) (via URL parameters):
```python
def main_page(pg: PageData) -> None:
    pg.page.add(Text(f'Main Page.', style=TextThemeStyle.DISPLAY_MEDIUM))

    text = TextField()

    pg.page.add(text, FilledButton('Send.', on_click=lambda _: pg.navigator.navigate(f'second_page?text={text.value}', pg.page)))

def second_page(pg: PageData) -> None:
    pg.page.add(Text(f'Second Page!', style=TextThemeStyle.DISPLAY_SMALL))

    for parameter in pg.parameters:
        pg.page.add(Text(f'{parameter}: {pg.parameters[parameter]}'))
```

<img src="https://i.imgur.com/XSF1QSr.gif" width=500>

Transferring classes, variables, or anything else (via arguments):
```python
def main_page(pg: PageData) -> None:
    pg.page.add(Text(f'Main Page.', style=TextThemeStyle.DISPLAY_MEDIUM))

    text = TextField()

    pg.page.add(text, FilledButton('Send.', on_click=lambda _: pg.navigator.navigate(f'second_page', pg.page, (text.value, ))))

def second_page(pg: PageData) -> None:
    pg.page.add(Text(f'Second Page!', style=TextThemeStyle.DISPLAY_SMALL))

    if pg.arguments:
        pg.page.add(Text(f'{pg.arguments[0]}'))
```

<img src="https://i.imgur.com/VQ58Yxj.gif" width=500>

**Comment by Plumpplump** [comment]
Hi, The example didn't work. The 2nd page didn't show as intended. Using navigator 2.1.3.

from flet import app, Page, Text, TextThemeStyle, TextField,FilledButton

from flet_navigator import VirtualFletNavigator, PageData, ROUTE_404

def main_page(pg: PageData) -> None:
    pg.page.add(Text(f'Main Page.', style=TextThemeStyle.DISPLAY_MEDIUM))

    text = TextField()

    pg.page.add(text, FilledButton('Send.', on_click=lambda _: pg.navigator.navigate(f'second_page?text={text.value}', pg.page)))

def second_page(pg: PageData) -> None:
    pg.page.add(Text(f'Second Page!', style=TextThemeStyle.DISPLAY_SMALL))

    for parameter in pg.parameters:
        pg.page.add(Text(f'{parameter}: {pg.parameters[parameter]}'))

def route_404(pg: PageData) -> None:
    ... # 404 Page Content.

def main(page: Page) -> None:
    # Initialize navigator.
    flet_navigator = VirtualFletNavigator(
        {
            '/': main_page, # Main page route.
            'second_page': second_page, # Second page route.
            ROUTE_404: route_404 # 404 page route.
        }, lambda route: print(f'Route changed!: {route}') # Route change handler (optional).
    )

    flet_navigator.render(page) # Render current page.

app(target=main)

**Comment by xzripper** [comment]
I forgot to specify that you should use `FletNavigator`, because `VirtualFletNavigator` doesn't support URL parameters.

**Comment by xzripper** [comment]
Read more about it in <a href="https://github.com/xzripper/flet_navigator/blob/main/flet-navigator-docs.md">documentation</a>.

**Comment by Plumpplump** [comment]
Works well now. Just finished a log in supabase and then manage student profile kind of test app.

**Comment by xzripper** [comment]
Great to hear! Good luck!
