### ISSUE TITLE
docs not complete why my app blank white

### ISSUE THREAD

**Issue by bobwatcherx** [xzripper/flet_navigator#5]
my code

from flet import *
from flet_navigator import VirtualFletNavigator, PageData, ROUTE_404

def home(pg:PageData):
	return AppBar(
		title=Text("home")
		)

def main(page:Page):
	flet_navigator = VirtualFletNavigator(
		{
			"/":home,
			},lambda route: print(f"nama rute :{route}")

			)
	flet_navigator.render(page)

flet.app(target=main)

**Comment by xzripper** [comment]
You should use `pg.page.add`, not return.

**Comment by xzripper** [comment]
And for appbar, you should use `pg.set_appbar(appbar)`

**Comment by bobwatcherx** [comment]
yes . thanks

**Comment by bobwatcherx** [comment]
i just didn't find any documentation for the page

for this 
def home(pg:PageData):
	pg.page.add(Text("Dqwdwq"))

thx

**Comment by xzripper** [comment]
Try updating (`pip install flet_navigator --upgrade`). Also `pg.set_appbar`, not `pg.page.set_appbar`.

**Comment by bobwatcherx** [comment]
thx solved

**Comment by bobwatcherx** [comment]
how to add custom transitions besides fade_effect

```
from flet import *
from flet_navigator import VirtualFletNavigator, PageData, ROUTE_404

def home(pg:PageData):
	myappbar = AppBar(
			title=Text("Dqwdqw"),
			bgcolor="blue"
			)
	pg.set_appbar(myappbar)
	pg.page.add(Text("Dqwdwq"))
	pg.page.add(
		ElevatedButton("goto page",
			on_click=lambda _: pg.navigator.navigate(f"about",pg.page,("tolol123"))
			)
		)


def about(pg:PageData):
	myappbar = AppBar(
			title=Text("About"),
			bgcolor="red"
			)
	pg.set_appbar(myappbar)
	pg.page.add(Text(f"ABOUT {pg.arguments[0]}",size=30))
	pg.page.add(
		ElevatedButton("goto page",
			on_click=lambda _: pg.navigator.navigate_homepage(pg.page)
			)
		)



def main(page:Page):
	flet_navigator = VirtualFletNavigator(
		{
			"/":home,
			"about":about,
			},lambda route: print(f"nama rute :{route}"),
		fade_effect=True
			)
	flet_navigator.render(page)


flet.app(target=main)
```

**Comment by xzripper** [comment]
Advanced animations coming in `V2.4.5` (in 5 minutes), please wait a little until release...

**Comment by xzripper** [comment]
Released! See documentation for advanced animations: https://github.com/xzripper/flet_navigator/blob/main/flet-navigator-docs.md#navigatoranimation
