### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by Plumpplump** [xzripper/flet_navigator#7]
**Describe your problem:**
It seems this code doesn't work anymore. I don't know why? 
error message:
 db= pg.arguments[0]
        ~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable



**Reproducing the problem:**
from flet import app, Page, Text, TextThemeStyle, TextField,FilledButton,WEB_BROWSER

from flet_navigator import FletNavigator, PageData, ROUTE_404
def main_page(pg: PageData) -> None:
    pg.page.add(Text(f'Main Page.', style=TextThemeStyle.DISPLAY_MEDIUM))

    text = TextField()
    db= pg.arguments[0]
    print(db)
    # print(school_db.get_grade())

    pg.page.add(text, FilledButton('Send.', on_click=lambda _: pg.navigator.navigate(f'second_page?text={text.value}', pg.page)))

def second_page(pg: PageData) -> None:
    pg.page.add(Text(f'Second Page!', style=TextThemeStyle.DISPLAY_SMALL))

    for parameter in pg.parameters:
        pg.page.add(Text(f'{parameter}: {pg.parameters[parameter]}'))

def route_404(pg: PageData) -> None:
    ... # 404 Page Content.

def login_page(pg: PageData) -> None:
    pg.navigator.navigate("main_page", pg.page, (1,))
    

def main(page: Page) -> None:
    # Initialize navigator.
    flet_navigator = FletNavigator(page, # Specify page.
        {
            '/': login_page, # Main page route,
            'main_page': main_page, # Main page route,
            'second_page': second_page, # Second page route,
            ROUTE_404: route_404 # 404 page route
        }, lambda route: print(f'Route changed!: {route}') # Route change handler (optional).
    )

    # Render current page.
    flet_navigator.render(page)

app(target=main)

**Media (optional):**
Screenshot or video..

**flet_navigator version, flet version, OS:**
`FletNavigator version, Flet Version, OS..`

**Additional:**
...

**Comment by Plumpplump** [comment]
and it seems set_route_data and get data don’t work on complex objects like instance of a class

**Comment by Plumpplump** [comment]
My use case is that I have a class variable that holds a connection to a remote database(supabase), I want to pass this variable among different pages.

**Comment by xzripper** [comment]
It happens because of bad redirect:
```python
pg.page.add(FilledButton("login", on_click=lambda _: pg.navigator.navigate("main_page", pg.page, (1,))))
```

And now everything works. Try to navigate to other pages via buttons or something else, its better for user and more secure.

**Comment by Plumpplump** [comment]
If I am in the “main_page”, and I want to redirect the data [1,] to the 2nd page using set_route_data,  do I write set_route_data(“main_page”, [1,]) or set_route_data(“second_page”, [1,])? Or I can put any string name?

**Comment by xzripper** [comment]
No, you should set route name as string, in what route you're storing data.

**Comment by Plumpplump** [comment]
I am confused. For example, I need to pass a database object to a sequence of pages, say there are 5 pages in my project.  Do I set like this: in the first page , set_route_data(“first page”, obj), in the 2nd page I get it by get_route_data(“first page”, obj)?  And again when I need to pass it to the 3rd page, do I set it again like set_route_data(“second page”, obj)… and so on until the 4th to 5th, I then write set_route_data(“fourth data”, obj)?

is this set_route_data, get_route_data, a alternative to .navigator. Navigate (“some page”, pg.page, obj)?

**Comment by xzripper** [comment]
Basically you can have your database saved on main page (set_route_data('main_page')), and then you can use get_route_data from any other Page. And no, this isn't alternative to arguments in navigate function.

**Comment by Plumpplump** [comment]
But I can also use navigator to pass on this database obj to different pages ,right?  Which way is better?

**Comment by xzripper** [comment]
Personally I created 'shared\db.py' folder\file, initialized database there and used 'from shared.db import db'. I think its better to share database between pages. Do however you like.

**Comment by yunguangli** [comment]
Thanks. following your advice, I modified my codes. much neater and cleaner and faster now.

**Comment by Plumpplump** [comment]
Vey nice. I modified. Much better now.

**Comment by xzripper** [comment]
Glad to hear!
