### ISSUE TITLE
__init__.py bug

### ISSUE THREAD

**Issue by Plumpplump** [xzripper/flet_navigator#8]
**Describe your problem:**
Line 466, if parameters is None, the len() statement will fail.

**Reproducing the problem:**
Code..

**Media (optional):**
Screenshot or video..

**flet_navigator version, flet version, OS:**
`FletNavigator version, Flet Version, OS..`

**Additional:**
...

**Comment by xzripper** [comment]
Thanks for report! Fixed in `V2.6.5`!
