### ISSUE TITLE
NavigationBar not showing 

### ISSUE THREAD

**Issue by yunguangli** [xzripper/flet_navigator#9]
**Describe your new feature:**
if I add a navigationbar (at the bottom of the screen),  and when I navigate to a second page, the navigationbar won't show ( I want to keep the same bar)  .  Maybe add an option to show/not show/add a new one.   Thanks 

**Additional:**
...

**Comment by xzripper** [comment]
You can use [`template`](https://github.com/xzripper/flet_navigator/blob/main/flet-navigator-docs.md#template) with [`PageData::set_appbar`](https://github.com/xzripper/flet_navigator/blob/main/flet-navigator-docs.md#pagedata)

Take a look at this example:
```python
def app_navbar(pg: PageData, args: Arguments) -> None:
    # Your NavigationBar code..

def main_page(pg: PageData) -> None:
    template(app_navbar, pg)

    # Other main page code..

def second_page(pg: PageData) -> None:
    template(app_navbar, pg)

    # Other second page code..
```

You can transfer arguments from page to template if your NavigationBar needs data from pages.

Is it fixed your problem?

**Comment by yunguangli** [comment]
seems to work. I will do more testing later , especially changing app bar and Navi bar's parameters in different pages. Thanks a lot.

**Comment by xzripper** [comment]
Happy to help!
